# Generated by Django 4.1.1 on 2022-09-21 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bones and joints", "Bones and Joints"),
                            ("digestive", "Digestive"),
                            ("cardiovascular", "Cardiovascular"),
                            ("imune boosters", "Imune Boosters"),
                            ("men health", "Men Health"),
                            ("beauty and longevity", "Beauty and Longevity"),
                            ("suma living", "Suma Living"),
                        ],
                        default="others",
                        max_length=60,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("pricing_unit", models.CharField(max_length=60)),
                ("number_in_stock", models.IntegerField(null=True)),
                (
                    "commodity_main_image",
                    models.ImageField(upload_to="images/commodities"),
                ),
                (
                    "commodity_extra_image1",
                    models.ImageField(null=True, upload_to="images/commodities"),
                ),
                (
                    "commodity_extra_image2",
                    models.ImageField(null=True, upload_to="images/commodities"),
                ),
            ],
        ),
    ]
