# Generated by Django 4.1.1 on 2023-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rojac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_main_image",
            field=models.ImageField(upload_to="product/inages"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="category_title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
