# Generated by Django 4.1.1 on 2023-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rojac", "0002_alter_product_product_main_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
