# Generated by Django 4.1.1 on 2022-09-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rojac", "0002_c2bpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="C2bBillRefNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_ref_number", models.CharField(max_length=12)),
                ("amount", models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name="c2bpayment",
            name="LastName",
        ),
        migrations.RemoveField(
            model_name="c2bpayment",
            name="MiddleName",
        ),
    ]
