# Generated by Django 4.1.1 on 2022-09-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rojac", "0003_c2bbillrefnumber_remove_c2bpayment_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="c2bpayment",
            name="MSISDN",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="c2bpayment",
            name="TransTime",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
