# Generated by Django 4.1.1 on 2022-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rojac", "0004_alter_c2bpayment_msisdn_alter_c2bpayment_transtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="c2bpayment",
            name="TransTime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
