# Generated by Django 4.1.1 on 2023-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rojac", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
